name: AdminChat
version: 1.0.0
api: [1.0.0,2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
author: SamyR0
main: AdminChat\ac
website: github.com/SamyR0
commands:
  adminchat:
    permission: pocketmine.broadcast.admin
    description: chat for staff
    usage: /ac <message>
    aliases: [ac]
